### ISSUE TITLE
How to use noTryAsync with axios.get(url);

### ISSUE THREAD

**Issue by abhisheikdeo** [Coly010/notry#1]
It's not a issue but mainly a question.

`import {noTryAsync} from "no-try";
import axios from "axios";

const url = "SOME_VALID_URL";
const {result, error} = noTryAsync(async () => await axios.get(url););
console.log(result, error); // This gives me undefined, undefined
`

Can you please help me with the appropriate way of using this?

**Comment by Coly010** [comment]
Hey, you have the async/await in the wrong place is all :)
```ts

import {noTryAsync} from "no-try";
import axios from "axios";

async myFunc() {
    const url = "SOME_VALID_URL";
    const {result, error} = await noTryAsync( 
        () => axios.get(url)
    );
}

myFunc();
```
Hope this helps.

**Comment by abhisheikdeo** [comment]
Even though it makes me look like an idiot, it definitely helps :)

**Comment by Coly010** [comment]
Glad it helps!
